version: "3.7"

services: 
    # copied from https://hub.docker.com/_/mysql/?tab=description
    mysql:
        image: mysql:8.0.21 #5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            # MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: azerty31$$
        ports:
            - 3306:3306
        volumes:
            - dotmim-mysql-data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    dotmim-mysql-data:
    

## docker cmd in powershell would be:
# docker run -d `
#   -v dotmim-mysql-data:/var/lib/mysql `
#   -e MYSQL_ALLOW_EMPTY_PASSWORD=yes `
#   -e MYSQL_DATABASE=test `
#   mysql:5.7